version: '3.8'

services:
  postgresql:
    container_name: postgres_db2
    build:
      context: ../
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - pgNetwork
  
  pgAdmin:  
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "8081:80"
    depends_on:
      - postgresql
    networks:
      - pgNetwork

volumes:
  postgres_data2:

networks:
  pgNetwork:
    driver: bridge