spring:
  application:
    name: libraryapi
#  profiles:
#    active: production
# SPRING_PROFILES_ACTIVE=production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        cursodsousa: trace
    org:
      springframework:
        web: debug
        security: trace

# trace
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'



springdoc:
  override-with-generic-response: false


# production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false


# homologacao
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/library