version: '3.8'

services:
  database:
    build:
      context: ../
      dockerfile: Dockerfile.mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 13246578
      MARIADB_DATABASE: mydb
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet7
  
  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8978"
    networks:
      - mynet7

volumes:
  mariadb_data:

networks:
  mynet7:
    driver: bridge
  
    